# ref: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml
singleuser:
  image:
    name: dholt/jupyterhub-k8s-gpu
    tag: latest
  extraEnv:
  - JUPYTER_ENABLE_LAB: 1
  nodeSelector:
    gpu: "true"
hub:
  cookieSecret: "<secret token>"
  prePuller:
    enabled: false
  extraConfig:
    10-gpu: |
      c.KubeSpawner.extra_resource_limits = { 'nvidia.com/gpu': 1 }
proxy:
  secretToken: "<secret token>"
